# Generated by Django 6.0.2 on 2026-03-05 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0002_alter_customuser_email_candidateprofile_hrprofile_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationMatchScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(default=0)),
                ('skill_overlap_pct', models.FloatField(default=0.0)),
                ('text_similarity_pct', models.FloatField(default=0.0)),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='match_score', to='recruitment.jobapplication')),
            ],
        ),
        migrations.CreateModel(
            name='ResumeParseResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_text', models.TextField(blank=True)),
                ('parsed_skills', models.TextField(blank=True, help_text='Comma-separated skills extracted from the resume')),
                ('parsed_experience_years', models.PositiveIntegerField(blank=True, null=True)),
                ('parsed_education', models.CharField(blank=True, max_length=400)),
                ('parsed_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parse_result', to='recruitment.candidateprofile')),
            ],
        ),
    ]
