# Generated by Django 6.0.2 on 2026-03-05 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0003_applicationmatchscore_resumeparseresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='gender',
            field=models.CharField(blank=True, help_text='Optional — used for diversity-aware hiring criteria', max_length=20),
        ),
        migrations.CreateModel(
            name='JobBiasCriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criterion', models.CharField(choices=[('experience_min', 'Minimum Experience (years)'), ('college_tier', 'College Tier (Tier 1 / Tier 2)'), ('gender', 'Gender Preference'), ('custom', 'Custom Keyword Rule')], max_length=20)),
                ('value', models.CharField(help_text="e.g. '5' for ≥5 years, 'Tier 1', 'Female', or a keyword phrase", max_length=200)),
                ('description', models.CharField(blank=True, help_text='Optional human-readable label shown on the HR dashboard', max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bias_criteria', to='recruitment.jobposting')),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationBiasResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passed', models.BooleanField()),
                ('detail', models.CharField(blank=True, max_length=300)),
                ('evaluated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bias_results', to='recruitment.jobapplication')),
                ('criterion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='recruitment.jobbiascriteria')),
            ],
            options={
                'unique_together': {('application', 'criterion')},
            },
        ),
    ]
